name: Cheapest operator

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    needs: run_flask
    strategy:
      matrix:
        python-version: [3.11.2]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          flask --app app run &
          pytest
          behave ./tests/features
      - name: Stop Flask app
        run: kill $(lsof -t -i:5000)
